### ISSUE TITLE
Obsidian.md

### ISSUE THREAD

**Issue by couleurm** [gluon-framework/examples#3]
Could someone much more clever than me on gluon (hi ducko 😚) 

and look into if it'd be possible to un-glue Obsidian's bloat and gluon our own browser to it?

#### Links
* [Website](https://obsidian.md/)
* [Source](https://github.com/obsidianmd?type=source)

**Comment by CanadaHonk** [comment]
It isn't open source (only plugin/theme things), so can't look into :P
